---
name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types:
      - opened
      - synchronize
      - reopened
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Check out code
        uses: actions/checkout@v3

      - uses: actions/setup-python@v4

      - uses: pre-commit/action@v3.0.0

      - name: Build
        run: go build -v ./...

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Lint chart
        run: helm lint chart

      - name: Template chart
        run: helm template chart

      - name: Package chart
        run: helm package chart
