---
name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.19
        uses: actions/setup-go@v4
        with:
          go-version: '1.19'

      - name: Check out code
        uses: actions/checkout@v3
        with:
          ref: ${{github.event.pull_request.head.sha}}

      - name: Download go dependencies
        run: go mod download

      - name: Run linter
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.50.0
          args: --timeout=3m

      - name: Run build
        run: go build

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Lint chart
        run: helm lint chart

      - name: Template chart
        run: helm template chart

      - name: Package chart
        run: helm package chart
